##set up the environment

In [ ]:
pip install requests

Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests) (2025.7.9)

In [ ]:
pip install html5lib

Requirement already satisfied: html5lib in /usr/local/lib/python3.11/dist-packages (1.1)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.11/dist-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.11/dist-packages (from html5lib) (0.5.1)

In [ ]:
pip install bs4

Collecting bs4
  Downloading bs4-0.0.2-py2.py3-none-any.whl.metadata (411 bytes)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.11/dist-packages (from bs4) (4.13.4)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->bs4) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4->bs4) (4.14.1)
Downloading bs4-0.0.2-py2.py3-none-any.whl (1.2 kB)
Installing collected packages: bs4
Successfully installed bs4-0.0.2

#importing libraries

In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [ ]:
url ="https://internshala.com/jobs/keywords-job/"

In [ ]:
r= requests.get(url)
htmlcontent= r.content #html content

In [ ]:
soup = BeautifulSoup(htmlcontent, 'html.parser')

In [ ]:
r #checking response

In [ ]:
#div elemet conatins all the info
job_infoo = soup.find_all('div', class_='container-fluid individual_internship view_detail_button visibilityTrackerItem')

In [ ]:
job_infoo

[<div class="container-fluid individual_internship view_detail_button visibilityTrackerItem" data-href="/job/detail/associate-telecaller-job-in-mumbai-at-hirewala1750166266" employment_type="job" id="individual_internship_2804952" internshipid="2804952" sequential_apply_referral="similar_internships">
 <div class="internship_meta experience_meta">
 <div class="internship-heading-container">
 <div class="company">
 <h3 class="job-internship-name">
 <a class="job-title-href" href="/job/detail/associate-telecaller-job-in-mumbai-at-hirewala1750166266" id="job_title" target="_blank">Associate Telecaller</a>
 </h3>
 <div class="heading_6 company_name">
 <div class="company_and_premium">
 <p class="company-name">
                             HireWala                        </p>
 <div class="actively-hiring-badge">Actively hiring</div>
 </div>
 </div>
 </div>
 <div class="internship_logo">
 <img alt="HireWala" src="/static/images/search/placeholder_logo.svg"/>
 </div>
 </div>
 <div class="individual_internship_details individual_internship_job">
 <div class="detail-row-1">
 <!-- locations -->
 <p class="row-1-item locations">
 <i class="ic-16-map-pin"></i>
 <span>
 <a>Mumbai</a> </span>
 </p>
 <!-- /locations  -->
 <!-- salary -->
 <div class="row-1-item">
 <i class="ic-16-money"></i>
 <span class="desktop">
                             ₹ 3,00,000 - 5,00,000                                    </span>
 <span class="mobile">
                         ₹ 3,00,000 - 5,00,000 /year                                </span>
 </div>
 <!-- /salary -->
 <!-- experience -->
 <div class="row-1-item">
 <i class="ic-16-briefcase"></i>
 <span>1 year(s)</span>
 </div>
 <!-- /experience -->
 </div>
 <div class="detail-row-2">
 <div class="color-labels">
 <div class="status-inactive"><i class="ic-16-reschedule"></i><span>3 weeks ago</span></div>
 </div>
 </div>
 </div>
 </div>
 </div>,
 <div class="container-fluid individual_internship view_detail_button visibilityTrackerItem" data-href="/job/detail/fresher-business-development-executive-job-in-kolkata-at-metguard1751628892" employment_type="job" id="individual_internship_2820744" internshipid="2820744" sequential_apply_referral="similar_internships">
 <div class="internship_meta experience_meta">
 <div class="internship-heading-container">
 <div class="company">
 <h3 class="job-internship-name">
 <a class="job-title-href" href="/job/detail/fresher-business-development-executive-job-in-kolkata-at-metguard1751628892" id="job_title" target="_blank">Business Development Executive</a>
 </h3>
 <div class="heading_6 company_name">
 <div class="company_and_premium">
 <p class="company-name">
                             METGUARD                        </p>
 <div class="actively-hiring-badge">Actively hiring</div>
 </div>
 </div>
 </div>
 <div class="internship_logo">
 <img alt="METGUARD" src="https://internshala-uploads.internshala.com/logo%2F1kjml8mykq6-89022.png.webp"/>
 </div>
 </div>
 <div class="individual_internship_details individual_internship_job">
 <div class="detail-row-1">
 <!-- locations -->
 <p class="row-1-item locations">
 <i class="ic-16-map-pin"></i>
 <span>
 <a>Kolkata</a> </span>
 </p>
 <!-- /locations  -->
 <!-- salary -->
 <div class="row-1-item">
 <i class="ic-16-money"></i>
 <span class="desktop">
                             ₹ 3,02,000 - 4,25,000                                    </span>
 <span class="mobile">
                         ₹ 3,02,000 - 4,25,000 /year                                </span>
 </div>
 <!-- /salary -->
 <!-- experience -->
 <div class="row-1-item">
 <i class="ic-16-briefcase"></i>
 <span>0 year(s)</span>
 </div>
 <!-- /experience -->
 </div>
 <div class="detail-row-2">
 <div class="color-labels">
 <div class="status-inactive"><i class="ic-16-reschedule"></i><span>1 week ago</span></div>
 </div>
 <div class="gray-labels">
 <div class="status-li">
 <div class="dot dot_1"></div>
 <span>Fresher  Job</span>
 </div>
 </div>
 </div>
 </div>
 </div>
 </div>,
 <div class="container-fluid individual_internship view_detail_button visibilityTrackerItem" data-href="/job/detail/fresher-electrical-engineer-job-in-rajasthan-at-varistor-solar1752149412" employment_type="job" id="individual_internship_2826286" internshipid="2826286" sequential_apply_referral="similar_internships">
 <div class="internship_meta experience_meta">
 <div class="internship-heading-container">
 <div class="company">
 <h3 class="job-internship-name">
 <a class="job-title-href" href="/job/detail/fresher-electrical-engineer-job-in-rajasthan-at-varistor-solar1752149412" id="job_title" target="_blank">Electrical Engineer</a>
 </h3>
 <div class="heading_6 company_name">
 <div class="company_and_premium">
 <p class="company-name">
                             Varistor Solar                        </p>
 <div class="actively-hiring-badge">Actively hiring</div>
 </div>
 </div>
 </div>
 <div class="internship_logo">
 <img alt="Varistor Solar" src="/static/images/search/placeholder_logo.svg"/>
 </div>
 </div>
 <div class="individual_internship_details individual_internship_job">
 <div class="detail-row-1">
 <!-- locations -->
 <p class="row-1-item locations">
 <i class="ic-16-map-pin"></i>
 <span>
 <a>Rajasthan</a> </span>
 </p>
 <!-- /locations  -->
 <!-- salary -->
 <div class="row-1-item">
 <i class="ic-16-money"></i>
 <span class="desktop">
                             ₹ 3,80,000 - 4,40,000                                    </span>
 <span class="mobile">
                         ₹ 3,80,000 - 4,40,000 /year                                </span>
 </div>
 <!-- /salary -->
 <!-- experience -->
 <div class="row-1-item">
 <i class="ic-16-briefcase"></i>
 <span>0 year(s)</span>
 </div>
 <!-- /experience -->
 </div>
 <div class="detail-row-2">
 <div class="color-labels">
 <div class="status-success"><i class="ic-16-reschedule"></i><span>2 days ago</span></div>
 <div class="early_applicant_wrapper">
 <img alt="early applicant icon" src="/static/images/icons/bolt_icon_color.svg"/>
 <span>Be an early applicant</span>
 </div>
 </div>
 <div class="gray-labels">
 <div class="status-li">
 <div class="dot dot_1"></div>
 <span>Fresher  Job</span>
 </div>
 </div>
 </div>
 </div>
 </div>
 </div>,
 <div class="container-fluid individual_internship view_detail_button visibilityTrackerItem" data-href="/job/detail/graphic-designer-job-in-meerut-at-stag-international1750656336" employment_type="job" id="individual_internship_2810703" internshipid="2810703" sequential_apply_referral="similar_internships">
 <div class="internship_meta experience_meta">
 <div class="internship-heading-container">
 <div class="company">
 <h3 class="job-internship-name">
 <a class="job-title-href" href="/job/detail/graphic-designer-job-in-meerut-at-stag-international1750656336" id="job_title" target="_blank">Graphic Designer</a>
 </h3>
 <div class="heading_6 company_name">
 <div class="company_and_premium">
 <p class="company-name">
                             Stag International                        </p>
 <div class="actively-hiring-badge">Actively hiring</div>
 </div>
 </div>
 </div>
 <div class="internship_logo">
 <img alt="Stag International" src="https://internshala-uploads.internshala.com/logo%2Fawht012h3es-18308.jpg.webp"/>
 </div>
 </div>
 <div class="individual_internship_details individual_internship_job">
 <div class="detail-row-1">
 <!-- locations -->
 <p class="row-1-item locations">
 <i class="ic-16-map-pin"></i>
 <span>
 <a>Meerut</a> </span>
 </p>
 <!-- /locations  -->
 <!-- salary -->
 <div class="row-1-item">
 <i class="ic-16-money"></i>
 <span class="desktop">
                             ₹ 4,20,000 - 4,80,000                                    </span>
 <span class="mobile">
                         ₹ 4,20,000 - 4,80,000 /year                                </span>
 </div>
 <!-- /salary -->
 <!-- experience -->
 <div class="row-1-item">
 <i class="ic-16-briefcase"></i>
 <span>1 year(s)</span>
 </div>
 <!-- /experience -->
 </div>
 <div class="detail-row-2">
 <div class="color-labels">
 <div class="status-inactive"><i class="ic-16-reschedule"></i><span>2 weeks ago</span></div>
 <div class="early_applicant_wrapper">
 <img alt="early applicant icon" src="/static/images/icons/bolt_icon_color.svg"/>
 <span>Be an early applicant</span>
 </div>
 </div>
 </div>
 </div>
 </div>
 </div>,
 <div class="container-fluid individual_internship view_detail_button visibilityTrackerItem" data-href="/job/detail/apparel-designer-job-in-meerut-at-stag-international1750395614" employment_type="job" id="individual_internship_2808664" internshipid="2808664" sequential_apply_referral="similar_internships">
 <div class="internship_meta experience_meta">
 <div class="internship-heading-container">
 <div class="company">
 <h3 class="job-internship-name">
 <a class="job-title-href" href="/job/detail/apparel-designer-job-in-meerut-at-stag-international1750395614" id="job_title" target="_blank">Apparel Designer</a>
 </h3>
 <div class="heading_6 company_name">
 <div class="company_and_premium">
 <p class="company-name">
                             Stag International                        </p>
 <div class="actively-hiring-badge">Actively hiring</div>
 </div>
 </div>
 </div>
 <div class="internship_logo">
 <img alt="Stag International" src="https://internshala-uploads.internshala.com/logo%2Fawht012h3es-18308.jpg.webp"/>
 </div>
 </div>
 <div class="individual_internship_details individual_internship_job">
 <div class="detail-row-1">
 <!-- locations -->
 <p class="row-1-item locations">
 <i class="ic-16-map-pin"></i>
 <span>
 <a>Meerut</a> </span>
 </p>
 <!-- /locations  -->
 <!-- salary -->
 <div class="row-1-item">
 <i class="ic-16-money"></i>
 <span class="desktop">
                             ₹ 2,60,000 - 2,80,000                                    </span>
 <span class="mobile">
                         ₹ 2,60,000 - 2,80,000 /year                                </span>
 </div>
 <!-- /salary -->
 <!-- experience -->
 <div class="row-1-item">
 <i class="ic-16-briefcase"></i>
 <span>1 year(s)</span>
 </div>
 <!-- /experience -->
 </div>
 <div class="detail-row-2">
 <div class="color-labels">
 <div class="status-inactive"><i class="ic-16-reschedule"></i><span>3 weeks ago</span></div>
 <div class="early_applicant_wrapper">
 <img alt="early applicant icon" src="/static/images/icons/bolt_icon_color.svg"/>
 <span>Be an early applicant</span>
 </div>
 </div>
 </div>
 </div>
 </div>
 </div>,
 <div class="container-fluid individual_internship view_detail_button visibilityTrackerItem" data-href="/job/detail/ecommerce-executive-job-in-meerut-at-stag-international1751968622" employment_type="job" id="individual_internship_2823522" internshipid="2823522" sequential_apply_referral="similar_internships">
 <div class="internship_meta experience_meta">
 <div class="internship-heading-container">
 <div class="company">
 <h3 class="job-internship-name">
 <a class="job-title-href" href="/job/detail/ecommerce-executive-job-in-meerut-at-stag-international1751968622" id="job_title" target="_blank">Ecommerce Executive</a>
 </h3>
 <div class="heading_6 company_name">
 <div class="company_and_premium">
 <p class="company-name">
                             Stag International                        </p>
 <div class="actively-hiring-badge">Actively hiring</div>
 </div>
 </div>
 </div>
 <div class="internship_logo">
 <img alt="Stag International" src="https://internshala-uploads.internshala.com/logo%2Fawht012h3es-18308.jpg.webp"/>
 </div>
 </div>
 <div class="individual_internship_details individual_internship_job">
 <div class="detail-row-1">
 <!-- locations -->
 <p class="row-1-item locations">
 <i class="ic-16-map-pin"></i>
 <span>
 <a>Meerut</a> </span>
 </p>
 <!-- /locations  -->
 <!-- salary -->
 <div class="row-1-item">
 <i class="ic-16-money"></i>
 <span class="desktop">
                             ₹ 3,00,000 - 3,60,000                                    </span>
 <span class="mobile">
                         ₹ 3,00,000 - 3,60,000 /year                                </span>
 </div>
 <!-- /salary -->
 <!-- experience -->
 <div class="row-1-item">
 <i class="ic-16-briefcase"></i>
 <span>1 year(s)</span>
 </div>
 <!-- /experience -->
 </div>
 <div class="detail-row-2">
 <div class="color-labels">
 <div class="status-info"><i class="ic-16-reschedule"></i><span>4 days ago</span></div>
 <div class="early_applicant_wrapper">
 <img alt="early applicant icon" src="/static/images/icons/bolt_icon_color.svg"/>
 <span>Be an early applicant</span>
 </div>
 </div>
 </div>
 </div>
 </div>
 </div>,
 <div class="container-fluid individual_internship view_detail_button visibilityTrackerItem" data-href="/job/detail/ai-driven-video-animation-creator-youtube-content-production-job-in-mumbai-at-startupcfos1750857680" employment_type="job" id="individual_internship_2811290" internshipid="2811290" sequential_apply_referral="similar_internships">
 <div class="internship_meta experience_meta">
 <div class="internship-heading-container">
 <div class="company">
 <h3 class="job-internship-name">
 <a class="job-title-href" href="/job/detail/ai-driven-video-animation-creator-youtube-content-production-job-in-mumbai-at-startupcfos1750857680" id="job_title" target="_blank">Video &amp; Animation Creator</a>
 </h3>
 <div class="heading_6 company_name">
 <div class="company_and_premium">
 <p class="company-name">
                             Startupcfos                        </p>
 <div class="actively-hiring-badge">Actively hiring</div>
 </div>
 </div>
 </div>
 <div class="internship_logo">
 <img alt="Startupcfos" src="/static/images/search/placeholder_logo.svg"/>
 </div>
 </div>
 <div class="individual_internship_details individual_internship_job">
 <div class="detail-row-1">
 <!-- locations -->
 <p class="row-1-item locations">
 <i class="ic-16-map-pin"></i>
 <span>
 <a>Mumbai</a> </span>
 </p>
 <!-- /locations  -->
 <!-- salary -->
 <div class="row-1-item">
 <i class="ic-16-money"></i>
 <span class="desktop">
                             ₹ 2,00,000 - 3,00,000                                    </span>
 <span class="mobile">
                         ₹ 2,00,000 - 3,00,000 /year                                </span>
 </div>
 <!-- /salary -->
 <!-- experience -->
 <div class="row-1-item">
 <i class="ic-16-briefcase"></i>
 <span>1 year(s)</span>
 </div>
 <!-- /experience -->
 </div>
 <div class="detail-row-2">
 <div class="color-labels">
 <div class="status-inactive"><i class="ic-16-reschedule"></i><span>2 weeks ago</span></div>
 <div class="early_applicant_wrapper">
 <img alt="early applicant icon" src="/static/images/icons/bolt_icon_color.svg"/>
 <span>Be an early applicant</span>
 </div>
 </div>
 </div>
 </div>
 </div>
 </div>,
 <div class="container-fluid individual_internship view_detail_button visibilityTrackerItem" data-href="/job/detail/creative-designer-job-in-bangalore-at-getreal1751968472" employment_type="job" id="individual_internship_2823480" internshipid="2823480" sequential_apply_referral="similar_internships">
 <div class="internship_meta experience_meta">
 <div class="internship-heading-container">
 <div class="company">
 <h3 class="job-internship-name">
 <a class="job-title-href" href="/job/detail/creative-designer-job-in-bangalore-at-getreal1751968472" id="job_title" target="_blank">Creative Designer</a>
 </h3>
 <div class="heading_6 company_name">
 <div class="company_and_premium">
 <p class="company-name">
                             GetREAL                        </p>
 <div class="actively-hiring-badge">Actively hiring</div>
 </div>
 </div>
 </div>
 <div class="internship_logo">
 <img alt="GetREAL" src="/static/images/search/placeholder_logo.svg"/>
 </div>
 </div>
 <div class="individual_internship_details individual_internship_job">
 <div class="detail-row-1">
 <!-- locations -->
 <p class="row-1-item locations">
 <i class="ic-16-map-pin"></i>
 <span>
 <a>Bangalore</a>                                                        (Hybrid)
                                     <span style="vertical-align: middle">
 <i class="pop ic-16-alert-circle office_days_popover" data-popover_content="2 day(s) in-office in a week"></i>
 </span>
 </span>
 </p>
 <!-- /locations  -->
 <!-- salary -->
 <div class="row-1-item">
 <i class="ic-16-money"></i>
 <span class="desktop">
                             ₹ 3,00,000                                    </span>
 <span class="mobile">
                         ₹ 3,00,000 /year                                </span>
 </div>
 <!-- /salary -->
 <!-- experience -->
 <div class="row-1-item">
 <i class="ic-16-briefcase"></i>
 <span>1 year(s)</span>
 </div>
 <!-- /experience -->
 </div>
 <div class="detail-row-2">
 <div class="color-labels">
 <div class="status-info"><i class="ic-16-reschedule"></i><span>4 days ago</span></div>
 </div>
 </div>
 </div>
 </div>
 </div>,
 <div class="container-fluid individual_internship view_detail_button visibilityTrackerItem" data-href="/job/detail/video-editor-job-in-vadodara-at-dreamfoot1751951961" employment_type="job" id="individual_internship_2823148" internshipid="2823148" sequential_apply_referral="similar_internships">
 <div class="internship_meta experience_meta">
 <div class="internship-heading-container">
 <div class="company">
 <h3 class="job-internship-name">
 <a class="job-title-href" href="/job/detail/video-editor-job-in-vadodara-at-dreamfoot1751951961" id="job_title" target="_blank">Video Editor</a>
 </h3>
 <div class="heading_6 company_name">
 <div class="company_and_premium">
 <p class="company-name">
                             Dreamfoot                        </p>
 <div class="actively-hiring-badge">Actively hiring</div>
 </div>
 </div>
 </div>
 <div class="internship_logo">
 <img alt="Dreamfoot" src="https://internshala-uploads.internshala.com/logo%2F618fc91fa21091636813087.png.webp"/>
 </div>
 </div>
 <div class="individual_internship_details individual_internship_job">
 <div class="detail-row-1">
 <!-- locations -->
 <p class="row-1-item locations">
 <i class="ic-16-map-pin"></i>
 <span>
 <a>Vadodara</a> </span>
 </p>
 <!-- /locations  -->
 <!-- salary -->
 <div class="row-1-item">
 <i class="ic-16-money"></i>
 <span class="desktop">
                             ₹ 2,00,000 - 3,00,000                                    </span>
 <span class="mobile">
                         ₹ 2,00,000 - 3,00,000 /year                                </span>
 </div>
 <!-- /salary -->
 <!-- experience -->
 <div class="row-1-item">
 <i class="ic-16-briefcase"></i>
 <span>1 year(s)</span>
 </div>
 <!-- /experience -->
 </div>
 <div class="detail-row-2">
 <div class="color-labels">
 <div class="status-info"><i class="ic-16-reschedule"></i><span>4 days ago</span></div>
 </div>
 </div>
 </div>
 </div>
 </div>,
 <div class="container-fluid individual_internship view_detail_button visibilityTrackerItem" data-href="/job/detail/psychologist-job-in-delhi-at-kapableclub1751545890" employment_type="job" id="individual_internship_2819912" internshipid="2819912" sequential_apply_referral="similar_internships">
 <div class="internship_meta experience_meta">
 <div class="internship-heading-container">
 <div class="company">
 <h3 class="job-internship-name">
 <a class="job-title-href" href="/job/detail/psychologist-job-in-delhi-at-kapableclub1751545890" id="job_title" target="_blank">Psychologist</a>
 </h3>
 <div class="heading_6 company_name">
 <div class="company_and_premium">
 <p class="company-name">
                             Kapable.club                        </p>
 </div>
 </div>
 </div>
 <div class="internship_logo">
 <img alt="Kapable.club" src="https://internshala-uploads.internshala.com/logo%2F61df00683b6be1642004584.png.webp"/>
 </div>
 </div>
 <div class="individual_internship_details individual_internship_job">
 <div class="detail-row-1">
 <!-- locations -->
 <p class="row-1-item locations">
 <i class="ic-16-map-pin"></i>
 <span>
 <a>Delhi</a> </span>
 </p>
 <!-- /locations  -->
 <!-- salary -->
 <div class="row-1-item">

In [ ]:
#next page link
next_page =soup.find('a', class_='pagination_block block').get("href")

In [ ]:
next_page

'/jobs/keywords-job/page-2/'

In [ ]:
current_next_page= "pagination_block block"+next_page

saving all the pages

In [ ]:
all_links= []

links = soup.find_all('a', class_='pagination_block block')
for link in links:
  next_page=link.get("href")
  current_next_page= "https://internshala.com/jobs/keywords-job/"+next_page
  all_links.append(current_next_page)
  print(current_next_page)

https://internshala.com/jobs/keywords-job//jobs/keywords-job/
https://internshala.com/jobs/keywords-job//jobs/keywords-job/page-205/
https://internshala.com/jobs/keywords-job//jobs/keywords-job/page-206/
https://internshala.com/jobs/keywords-job//jobs/keywords-job/page-207/
https://internshala.com/jobs/keywords-job//jobs/keywords-job/page-208/
https://internshala.com/jobs/keywords-job//jobs/keywords-job/page-209/
https://internshala.com/jobs/keywords-job//jobs/keywords-job/
https://internshala.com/jobs/keywords-job//jobs/keywords-job/page-207/
https://internshala.com/jobs/keywords-job//jobs/keywords-job/page-208/
https://internshala.com/jobs/keywords-job//jobs/keywords-job/page-209/

##now scrapping

In [ ]:
job_role=[]
Company=[]
Salary =[]
Location=[]

base_url = "https://internshala.com"
url = base_url + "/jobs/keywords-job/"

In [ ]:
while url:
    print(f"Scraping: {url}")
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')

    job_infoo = soup.find_all('div', class_='container-fluid individual_internship view_detail_button visibilityTrackerItem')

    #jobrole
    for job in job_infoo:
        role_tag = job.find('a', class_='job-title-href')
        role = role_tag.text.strip() if role_tag else "N/A"
        job_role.append(role)

    #company
    for job in job_infoo:
        company_tag = job.find('p', class_='company-name')
        company = company_tag.text.strip() if company_tag else "N/A"
        Company.append(company)


    #Salary
    for job in job_infoo:
        salary_tag = job.find('span', class_='desktop')
        salary = salary_tag.text.strip() if salary_tag else "N/A"
        Salary.append(salary)

    #location
    for job in job_infoo:
        location_tag = job.find('p', class_='row-1-item locations')
        location = location_tag.text.strip() if location_tag else "N/A"
        Location.append(location)


            # Find next page
    next_btn = soup.find('a', class_='next_page')
    if next_btn and next_btn.get('href'):
        next_page = next_btn.get('href')
        url = base_url + next_page
    else:
        break

Scraping: https://internshala.com/jobs/keywords-job/
Scraping: https://internshala.com/jobs/keywords-job/page-2/
Scraping: https://internshala.com/jobs/keywords-job/page-3/
Scraping: https://internshala.com/jobs/keywords-job/page-4/
Scraping: https://internshala.com/jobs/keywords-job/page-5/
Scraping: https://internshala.com/jobs/keywords-job/page-6/
Scraping: https://internshala.com/jobs/keywords-job/page-7/
Scraping: https://internshala.com/jobs/keywords-job/page-8/
Scraping: https://internshala.com/jobs/keywords-job/page-9/
Scraping: https://internshala.com/jobs/keywords-job/page-10/
Scraping: https://internshala.com/jobs/keywords-job/page-11/
Scraping: https://internshala.com/jobs/keywords-job/page-12/
Scraping: https://internshala.com/jobs/keywords-job/page-13/
Scraping: https://internshala.com/jobs/keywords-job/page-14/
Scraping: https://internshala.com/jobs/keywords-job/page-15/
Scraping: https://internshala.com/jobs/keywords-job/page-16/
Scraping: https://internshala.com/jobs/keywords-job/page-17/
Scraping: https://internshala.com/jobs/keywords-job/page-18/
Scraping: https://internshala.com/jobs/keywords-job/page-19/
Scraping: https://internshala.com/jobs/keywords-job/page-20/
Scraping: https://internshala.com/jobs/keywords-job/page-21/
Scraping: https://internshala.com/jobs/keywords-job/page-22/
Scraping: https://internshala.com/jobs/keywords-job/page-23/
Scraping: https://internshala.com/jobs/keywords-job/page-24/
Scraping: https://internshala.com/jobs/keywords-job/page-25/
Scraping: https://internshala.com/jobs/keywords-job/page-26/
Scraping: https://internshala.com/jobs/keywords-job/page-27/
Scraping: https://internshala.com/jobs/keywords-job/page-28/
Scraping: https://internshala.com/jobs/keywords-job/page-29/
Scraping: https://internshala.com/jobs/keywords-job/page-30/
Scraping: https://internshala.com/jobs/keywords-job/page-31/
Scraping: https://internshala.com/jobs/keywords-job/page-32/
Scraping: https://internshala.com/jobs/keywords-job/page-33/
Scraping: https://internshala.com/jobs/keywords-job/page-34/
Scraping: https://internshala.com/jobs/keywords-job/page-35/
Scraping: https://internshala.com/jobs/keywords-job/page-36/
Scraping: https://internshala.com/jobs/keywords-job/page-37/
Scraping: https://internshala.com/jobs/keywords-job/page-38/
Scraping: https://internshala.com/jobs/keywords-job/page-39/
Scraping: https://internshala.com/jobs/keywords-job/page-40/
Scraping: https://internshala.com/jobs/keywords-job/page-41/
Scraping: https://internshala.com/jobs/keywords-job/page-42/
Scraping: https://internshala.com/jobs/keywords-job/page-43/
Scraping: https://internshala.com/jobs/keywords-job/page-44/
Scraping: https://internshala.com/jobs/keywords-job/page-45/
Scraping: https://internshala.com/jobs/keywords-job/page-46/
Scraping: https://internshala.com/jobs/keywords-job/page-47/
Scraping: https://internshala.com/jobs/keywords-job/page-48/
Scraping: https://internshala.com/jobs/keywords-job/page-49/
Scraping: https://internshala.com/jobs/keywords-job/page-50/
Scraping: https://internshala.com/jobs/keywords-job/page-51/
Scraping: https://internshala.com/jobs/keywords-job/page-52/
Scraping: https://internshala.com/jobs/keywords-job/page-53/
Scraping: https://internshala.com/jobs/keywords-job/page-54/
Scraping: https://internshala.com/jobs/keywords-job/page-55/
Scraping: https://internshala.com/jobs/keywords-job/page-56/
Scraping: https://internshala.com/jobs/keywords-job/page-57/
Scraping: https://internshala.com/jobs/keywords-job/page-58/
Scraping: https://internshala.com/jobs/keywords-job/page-59/
Scraping: https://internshala.com/jobs/keywords-job/page-60/
Scraping: https://internshala.com/jobs/keywords-job/page-61/
Scraping: https://internshala.com/jobs/keywords-job/page-62/
Scraping: https://internshala.com/jobs/keywords-job/page-63/
Scraping: https://internshala.com/jobs/keywords-job/page-64/
Scraping: https://internshala.com/jobs/keywords-job/page-65/
Scraping: https://internshala.com/jobs/keywords-job/page-66/
Scraping: https://internshala.com/jobs/keywords-job/page-67/
Scraping: https://internshala.com/jobs/keywords-job/page-68/
Scraping: https://internshala.com/jobs/keywords-job/page-69/
Scraping: https://internshala.com/jobs/keywords-job/page-70/
Scraping: https://internshala.com/jobs/keywords-job/page-71/
Scraping: https://internshala.com/jobs/keywords-job/page-72/
Scraping: https://internshala.com/jobs/keywords-job/page-73/
Scraping: https://internshala.com/jobs/keywords-job/page-74/
Scraping: https://internshala.com/jobs/keywords-job/page-75/
Scraping: https://internshala.com/jobs/keywords-job/page-76/
Scraping: https://internshala.com/jobs/keywords-job/page-77/
Scraping: https://internshala.com/jobs/keywords-job/page-78/
Scraping: https://internshala.com/jobs/keywords-job/page-79/
Scraping: https://internshala.com/jobs/keywords-job/page-80/
Scraping: https://internshala.com/jobs/keywords-job/page-81/
Scraping: https://internshala.com/jobs/keywords-job/page-82/
Scraping: https://internshala.com/jobs/keywords-job/page-83/
Scraping: https://internshala.com/jobs/keywords-job/page-84/
Scraping: https://internshala.com/jobs/keywords-job/page-85/
Scraping: https://internshala.com/jobs/keywords-job/page-86/
Scraping: https://internshala.com/jobs/keywords-job/page-87/
Scraping: https://internshala.com/jobs/keywords-job/page-88/
Scraping: https://internshala.com/jobs/keywords-job/page-89/
Scraping: https://internshala.com/jobs/keywords-job/page-90/
Scraping: https://internshala.com/jobs/keywords-job/page-91/
Scraping: https://internshala.com/jobs/keywords-job/page-92/
Scraping: https://internshala.com/jobs/keywords-job/page-93/
Scraping: https://internshala.com/jobs/keywords-job/page-94/
Scraping: https://internshala.com/jobs/keywords-job/page-95/
Scraping: https://internshala.com/jobs/keywords-job/page-96/
Scraping: https://internshala.com/jobs/keywords-job/page-97/
Scraping: https://internshala.com/jobs/keywords-job/page-98/
Scraping: https://internshala.com/jobs/keywords-job/page-99/
Scraping: https://internshala.com/jobs/keywords-job/page-100/
Scraping: https://internshala.com/jobs/keywords-job/page-101/
Scraping: https://internshala.com/jobs/keywords-job/page-102/
Scraping: https://internshala.com/jobs/keywords-job/page-103/
Scraping: https://internshala.com/jobs/keywords-job/page-104/
Scraping: https://internshala.com/jobs/keywords-job/page-105/
Scraping: https://internshala.com/jobs/keywords-job/page-106/
Scraping: https://internshala.com/jobs/keywords-job/page-107/
Scraping: https://internshala.com/jobs/keywords-job/page-108/
Scraping: https://internshala.com/jobs/keywords-job/page-109/
Scraping: https://internshala.com/jobs/keywords-job/page-110/
Scraping: https://internshala.com/jobs/keywords-job/page-111/
Scraping: https://internshala.com/jobs/keywords-job/page-112/
Scraping: https://internshala.com/jobs/keywords-job/page-113/
Scraping: https://internshala.com/jobs/keywords-job/page-114/
Scraping: https://internshala.com/jobs/keywords-job/page-115/
Scraping: https://internshala.com/jobs/keywords-job/page-116/
Scraping: https://internshala.com/jobs/keywords-job/page-117/
Scraping: https://internshala.com/jobs/keywords-job/page-118/
Scraping: https://internshala.com/jobs/keywords-job/page-119/
Scraping: https://internshala.com/jobs/keywords-job/page-120/
Scraping: https://internshala.com/jobs/keywords-job/page-121/
Scraping: https://internshala.com/jobs/keywords-job/page-122/
Scraping: https://internshala.com/jobs/keywords-job/page-123/
Scraping: https://internshala.com/jobs/keywords-job/page-124/
Scraping: https://internshala.com/jobs/keywords-job/page-125/
Scraping: https://internshala.com/jobs/keywords-job/page-126/
Scraping: https://internshala.com/jobs/keywords-job/page-127/
Scraping: https://internshala.com/jobs/keywords-job/page-128/
Scraping: https://internshala.com/jobs/keywords-job/page-129/
Scraping: https://internshala.com/jobs/keywords-job/page-130/
Scraping: https://internshala.com/jobs/keywords-job/page-131/
Scraping: https://internshala.com/jobs/keywords-job/page-132/
Scraping: https://internshala.com/jobs/keywords-job/page-133/
Scraping: https://internshala.com/jobs/keywords-job/page-134/
Scraping: https://internshala.com/jobs/keywords-job/page-135/
Scraping: https://internshala.com/jobs/keywords-job/page-136/
Scraping: https://internshala.com/jobs/keywords-job/page-137/
Scraping: https://internshala.com/jobs/keywords-job/page-138/
Scraping: https://internshala.com/jobs/keywords-job/page-139/
Scraping: https://internshala.com/jobs/keywords-job/page-140/
Scraping: https://internshala.com/jobs/keywords-job/page-141/
Scraping: https://internshala.com/jobs/keywords-job/page-142/
Scraping: https://internshala.com/jobs/keywords-job/page-143/
Scraping: https://internshala.com/jobs/keywords-job/page-144/
Scraping: https://internshala.com/jobs/keywords-job/page-145/
Scraping: https://internshala.com/jobs/keywords-job/page-146/
Scraping: https://internshala.com/jobs/keywords-job/page-147/
Scraping: https://internshala.com/jobs/keywords-job/page-148/
Scraping: https://internshala.com/jobs/keywords-job/page-149/
Scraping: https://internshala.com/jobs/keywords-job/page-150/
Scraping: https://internshala.com/jobs/keywords-job/page-151/
Scraping: https://internshala.com/jobs/keywords-job/page-152/
Scraping: https://internshala.com/jobs/keywords-job/page-153/
Scraping: https://internshala.com/jobs/keywords-job/page-154/
Scraping: https://internshala.com/jobs/keywords-job/page-155/
Scraping: https://internshala.com/jobs/keywords-job/page-156/
Scraping: https://internshala.com/jobs/keywords-job/page-157/
Scraping: https://internshala.com/jobs/keywords-job/page-158/
Scraping: https://internshala.com/jobs/keywords-job/page-159/
Scraping: https://internshala.com/jobs/keywords-job/page-160/
Scraping: https://internshala.com/jobs/keywords-job/page-161/
Scraping: https://internshala.com/jobs/keywords-job/page-162/
Scraping: https://internshala.com/jobs/keywords-job/page-163/
Scraping: https://internshala.com/jobs/keywords-job/page-164/
Scraping: https://internshala.com/jobs/keywords-job/page-165/
Scraping: https://internshala.com/jobs/keywords-job/page-166/
Scraping: https://internshala.com/jobs/keywords-job/page-167/
Scraping: https://internshala.com/jobs/keywords-job/page-168/
Scraping: https://internshala.com/jobs/keywords-job/page-169/
Scraping: https://internshala.com/jobs/keywords-job/page-170/
Scraping: https://internshala.com/jobs/keywords-job/page-171/
Scraping: https://internshala.com/jobs/keywords-job/page-172/
Scraping: https://internshala.com/jobs/keywords-job/page-173/
Scraping: https://internshala.com/jobs/keywords-job/page-174/
Scraping: https://internshala.com/jobs/keywords-job/page-175/
Scraping: https://internshala.com/jobs/keywords-job/page-176/
Scraping: https://internshala.com/jobs/keywords-job/page-177/
Scraping: https://internshala.com/jobs/keywords-job/page-178/
Scraping: https://internshala.com/jobs/keywords-job/page-179/
Scraping: https://internshala.com/jobs/keywords-job/page-180/
Scraping: https://internshala.com/jobs/keywords-job/page-181/
Scraping: https://internshala.com/jobs/keywords-job/page-182/
Scraping: https://internshala.com/jobs/keywords-job/page-183/
Scraping: https://internshala.com/jobs/keywords-job/page-184/
Scraping: https://internshala.com/jobs/keywords-job/page-185/
Scraping: https://internshala.com/jobs/keywords-job/page-186/
Scraping: https://internshala.com/jobs/keywords-job/page-187/
Scraping: https://internshala.com/jobs/keywords-job/page-188/
Scraping: https://internshala.com/jobs/keywords-job/page-189/
Scraping: https://internshala.com/jobs/keywords-job/page-190/
Scraping: https://internshala.com/jobs/keywords-job/page-191/
Scraping: https://internshala.com/jobs/keywords-job/page-192/
Scraping: https://internshala.com/jobs/keywords-job/page-193/
Scraping: https://internshala.com/jobs/keywords-job/page-194/
Scraping: https://internshala.com/jobs/keywords-job/page-195/
Scraping: https://internshala.com/jobs/keywords-job/page-196/
Scraping: https://internshala.com/jobs/keywords-job/page-197/
Scraping: https://internshala.com/jobs/keywords-job/page-198/
Scraping: https://internshala.com/jobs/keywords-job/page-199/
Scraping: https://internshala.com/jobs/keywords-job/page-200/
Scraping: https://internshala.com/jobs/keywords-job/page-201/
Scraping: https://internshala.com/jobs/keywords-job/page-202/
Scraping: https://internshala.com/jobs/keywords-job/page-203/
Scraping: https://internshala.com/jobs/keywords-job/page-204/
Scraping: https://internshala.com/jobs/keywords-job/page-205/
Scraping: https://internshala.com/jobs/keywords-job/page-206/
Scraping: https://internshala.com/jobs/keywords-job/page-207/
Scraping: https://internshala.com/jobs/keywords-job/page-208/
Scraping: https://internshala.com/jobs/keywords-job/page-209/
Scraping: https://internshala.com/jobs/keywords-job/page-210/

In [ ]:
print(len(job_role), len(Company), len(Location),len(Salary),len(Location))

8388 8388 8388 8388 8388

#converting into dataframes

In [ ]:
df= pd.DataFrame({"JOB Role": job_role, "Company":Company ,"Salary":Salary,"Location":Location})
df

,JOB Role,Company,Salary,Location
0,Associate Telecaller,HireWala,"₹ 3,00,000 - 5,00,000",Mumbai
1,Business Development Executive,METGUARD,"₹ 3,02,000 - 4,25,000",Kolkata
2,Graphic Designer,Stag International,"₹ 4,20,000 - 4,80,000",Meerut
3,Electrical Engineer,Varistor Solar,"₹ 3,80,000 - 4,40,000",Rajasthan
4,Ecommerce Executive,Stag International,"₹ 3,00,000 - 3,60,000",Meerut
...,...,...,...,...
8383,Client Technology Campus Hire FY 26 - Product ...,EY,Competitive salary,Bangalore
8384,Client Technology Campus Hire FY 26 - Product ...,EY,Competitive salary,Pune
8385,Omni Sport Advisor/Store Customer Service Advisor,Decathlon,Competitive salary,Gautam Buddh Nagar
8386,Social Media Marketing Manager,WhizCo | Creative Tech And Influencer Marketing,Competitive salary,Delhi
8387,Programmer Analyst Trainee / Programmer Analys...,Cognizant,"₹ 4,00,000 - 6,75,000","Bhubaneswar, Chennai, Coimbatore, Kolkata, Pun..."

#saving the dataset

In [ ]:
# Save the DataFrame as a CSV file
df.to_csv("Internshala_scraped_jobs.csv", index=False)

# Download the CSV file
from google.colab import files
files.download("Internshala_scraped_jobs.csv")

In [ ]:
df.head()

,JOB Role,Company,Salary,Location
0,Associate Telecaller,HireWala,"₹ 3,00,000 - 5,00,000",Mumbai
1,Business Development Executive,METGUARD,"₹ 3,02,000 - 4,25,000",Kolkata
2,Graphic Designer,Stag International,"₹ 4,20,000 - 4,80,000",Meerut
3,Electrical Engineer,Varistor Solar,"₹ 3,80,000 - 4,40,000",Rajasthan
4,Ecommerce Executive,Stag International,"₹ 3,00,000 - 3,60,000",Meerut